### ISSUE TITLE
Typo in the Engine Support Server Level name.

### ISSUE THREAD

**Issue by LonwoLonwo** [MyCATApache/Mycat2#606]
Hello.

Our user has encountered a problem when connecting to the MySQL database with Mycat2 help.
The problem described here: https://github.com/dbeaver/dbeaver/issues/14646

And I think that the typo is here:
https://github.com/MyCATApache/Mycat2/blob/75331e6c9c46c646609a56cfec76bbdfc8728a1b/hbt/src/main/java/io/mycat/prototypeserver/mysql/PrototypeHandlerImpl.java#L291
and here:
https://github.com/MyCATApache/Mycat2/blob/ed74f7acbfb5a1ca270aba6cd674e8b26767716c/mycat2/src/main/java/io/mycat/sqlhandler/dql/ShowEnginesSQLHandler.java#L45

I wanted to do a pull request, but `Permission to MyCATApache/Mycat2.git denied to LonwoLonwo`.

Server's level of support: https://dev.mysql.com/doc/refman/8.0/en/show-engines.html

**Comment by junwen12221** [comment]
I have sent an invitation with write permission to you.
There may be a misspelled "drfault".
I will test it with dbeaver.

**Comment by LonwoLonwo** [comment]
@junwen12221 
Thanks! 
Here is the PR https://github.com/MyCATApache/Mycat2/pull/607

**Comment by LonwoLonwo** [comment]
Hello @junwen12221 
If there are any problems when testing with DBeaver, please let me know.

**Comment by junwen12221** [comment]
> Hello @junwen12221 If there are any problems when testing with DBeaver, please let me know.

Thank you. After I fix several spelling mistakes, 'dbeaver' can connect to mycat2 and perform table creation and query on mycat2. I have sent the repaired version to that user.

https://github.com/MyCATApache/Mycat2/commit/4d6ae22e7a14b8a07d697bffb7510fb20da16b52

![image](https://user-images.githubusercontent.com/11361391/143235981-dea5eb3c-be30-4d94-94a4-75b547739c28.png)

During this process, I found that the exception information of 'dbeaver' is not friendly enough. Or we can make '\ dbeaver \ plugins' into an independent jar and publish it in Maven repository. It can run independently (test the database connected to the data source), so that database (Middleware) developers like us can adapt the database graphical client ('dbeaver')
